### ISSUE TITLE
Blockquotes are not rendered

### ISSUE THREAD

**Issue by rgreinho** [codeandmedia/zola_easydocs_theme#9]
The theme does not render blockquotes. They are simply indented.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#blockquotes=

**Comment by c-git** [comment]
Do you have an example that you can share where it doesn't work?

**Comment by rgreinho** [comment]
Nothing online yet, but I can share a snippet of what I am working on.

This markdown:

```md
## Setup the local dev environment

> **REMARK: make sure to run the commands in the correct folder.**
```

Renders as:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/6969134/177012851-60e54343-3afe-422e-b0fa-d07a01b9bcb2.png">

To adjust it, I added this to the `main.css` file:

```css
blockquote {
  border-left: #808080 8px solid;
  margin: 0;
  background-color: #dcdcdc;
  padding: 0 20px;
}
```

And now it looks like this:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/6969134/177012901-39aea6e3-5d7d-4b94-a2fb-036f462fec7f.png">
